AllCops:
  TargetRubyVersion: "2.4.0"
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - sma-front/**/*
    - app/models/concerns/node_relation_helper.rb
    - node_modules/**/*

OrderedGems:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

GuardClause:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Max: 66

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 90

# Offense count: 2
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Offense count: 9
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 174

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 150
